### ISSUE TITLE
[BUG] [1.0.1-alpha07] Incompatibility with "androidx.navigation:navigation-compose:2.6.0"

### ISSUE THREAD

**Issue by Papes96** [microsoft/surface-duo-sdk#124]
## 🐛 Describe the bug
I found that after updating the navigation-compose dependency to 2.6.0 the `navigateToPane2()` function crashes with the following log: 

`FATAL EXCEPTION: main
Process: com.xxx.xxx, PID: 12507
java.lang.NoSuchMethodError: No virtual method getBackQueue()Lkotlin/collections/ArrayDeque; in class Landroidx/navigation/NavHostController; or its super classes (declaration of 'androidx.navigation.NavHostController' appears in /data/app/~~phM2qZ5vae1iOopB_iXCPg==/com.xxx.xxx-QMpXgWBhbZ6qhfai2lCApw==/base.apk!classes15.dex)
at com.microsoft.device.dualscreen.twopanelayout.twopanelayout.TwoPaneLayoutCoreKt$SinglePaneContainer$3.invoke(TwoPaneLayoutCore.kt:72)
at com.microsoft.device.dualscreen.twopanelayout.twopanelayout.TwoPaneLayoutCoreKt$SinglePaneContainer$3.invoke(TwoPaneLayoutCore.kt:71)`

## ⚠️ Current behavior
`FATAL EXCEPTION: main
Process: com.xxx.xxx, PID: 12507
java.lang.NoSuchMethodError: No virtual method getBackQueue()Lkotlin/collections/ArrayDeque; in class Landroidx/navigation/NavHostController; or its super classes (declaration of 'androidx.navigation.NavHostController' appears in /data/app/~~phM2qZ5vae1iOopB_iXCPg==/com.xxx.xxx-QMpXgWBhbZ6qhfai2lCApw==/base.apk!classes15.dex)
at com.microsoft.device.dualscreen.twopanelayout.twopanelayout.TwoPaneLayoutCoreKt$SinglePaneContainer$3.invoke(TwoPaneLayoutCore.kt:72)
at com.microsoft.device.dualscreen.twopanelayout.twopanelayout.TwoPaneLayoutCoreKt$SinglePaneContainer$3.invoke(TwoPaneLayoutCore.kt:71)`

## ✔️ Expected behavior
No crash

## 🪜 Steps to reproduce
1. Add the following dependencies
`androidx.navigation:navigation-compose:2.6.0`
`com.microsoft.device.dualscreen:twopanelayout:1.0.1-alpha07`
2. Use the function `navigateToPane2()`
3. App crashes

## 📱 Tech info
- Name of the library: com.microsoft.device.dualscreen:twopanelayout
- Library/App version: 1.0.1-alpha07
- Device/emulator version/model: Pixel 6
- OS: SDK 34

**Comment by khalp** [comment]
Hi @Papes96, thanks for reporting this! Since this is a `TwoPaneLayout` bug, could you please open an issue in the https://github.com/microsoft/surface-duo-compose-sdk repo instead? Thanks!
